-- Generated by http://csv2sql.com online CSV to SQL converter

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('4','Afghanistan','AFG');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('248','Åland Islands','ALA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('8','Albania','ALB');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('12','Algeria','DZA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('16','American Samoa','ASM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('20','Andorra','AND');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('24','Angola','AGO');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('660','Anguilla','AIA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('28','Antigua and Barbuda','ATG');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('32','Argentina','ARG');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('51','Armenia','ARM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('533','Aruba','ABW');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('36','Australia','AUS');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('40','Austria','AUT');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('31','Azerbaijan','AZE');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('44','Bahamas','BHS');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('48','Bahrain','BHR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('50','Bangladesh','BGD');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('52','Barbados','BRB');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('112','Belarus','BLR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('56','Belgium','BEL');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('84','Belize','BLZ');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('204','Benin','BEN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('60','Bermuda','BMU');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('64','Bhutan','BTN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('68','Bolivia (Plurinational State of)','BOL');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('535','Bonaire, Saint Eustatius and Saba','BES');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('70','Bosnia and Herzegovina','BIH');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('72','Botswana','BWA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('76','Brazil','BRA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('92','British Virgin Islands','VGB');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('96','Brunei Darussalam','BRN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('100','Bulgaria','BGR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('854','Burkina Faso','BFA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('108','Burundi','BDI');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('116','Cambodia','KHM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('120','Cameroon','CMR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('124','Canada','CAN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('132','Cape Verde','CPV');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('136','Cayman Islands','CYM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('140','Central African Republic','CAF');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('148','Chad','TCD');

INSERT INTO countries (`country_numerical_code`,`country_name`) VALUES ('830','Channel Islands');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('152','Chile','CHL');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('156','China','CHN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('344','China, Hong Kong Special Administrative Region','HKG');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('446','China, Macao Special Administrative Region','MAC');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('170','Colombia','COL');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('174','Comoros','COM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('178','Congo','COG');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('184','Cook Islands','COK');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('188','Costa Rica','CRI');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('384','Côte d\'Ivoire','CIV');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('191','Croatia','HRV');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('192','Cuba','CUB');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('531','Curaçao','CUW');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('196','Cyprus','CYP');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('203','Czech Republic','CZE');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('408','Democratic People\'s Republic of Korea','PRK');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('180','Democratic Republic of the Congo','COD');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('208','Denmark','DNK');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('262','Djibouti','DJI');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('212','Dominica','DMA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('214','Dominican Republic','DOM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('218','Ecuador','ECU');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('818','Egypt','EGY');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('222','El Salvador','SLV');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('226','Equatorial Guinea','GNQ');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('232','Eritrea','ERI');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('233','Estonia','EST');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('231','Ethiopia','ETH');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('234','Faeroe Islands','FRO');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('238','Falkland Islands (Malvinas)','FLK');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('242','Fiji','FJI');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('246','Finland','FIN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('250','France','FRA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('254','French Guiana','GUF');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('258','French Polynesia','PYF');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('266','Gabon','GAB');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('270','Gambia','GMB');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('268','Georgia','GEO');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('276','Germany','DEU');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('288','Ghana','GHA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('292','Gibraltar','GIB');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('300','Greece','GRC');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('304','Greenland','GRL');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('308','Grenada','GRD');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('312','Guadeloupe','GLP');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('316','Guam','GUM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('320','Guatemala','GTM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('831','Guernsey','GGY');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('324','Guinea','GIN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('624','Guinea-Bissau','GNB');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('328','Guyana','GUY');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('332','Haiti','HTI');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('336','Holy See','VAT');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('340','Honduras','HND');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('348','Hungary','HUN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('352','Iceland','ISL');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('356','India','IND');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('360','Indonesia','IDN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('364','Iran (Islamic Republic of)','IRN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('368','Iraq','IRQ');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('372','Ireland','IRL');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('833','Isle of Man','IMN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('376','Israel','ISR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('380','Italy','ITA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('388','Jamaica','JAM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('392','Japan','JPN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('832','Jersey','JEY');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('400','Jordan','JOR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('398','Kazakhstan','KAZ');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('404','Kenya','KEN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('296','Kiribati','KIR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('414','Kuwait','KWT');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('417','Kyrgyzstan','KGZ');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('418','Lao People\'s Democratic Republic','LAO');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('428','Latvia','LVA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('422','Lebanon','LBN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('426','Lesotho','LSO');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('430','Liberia','LBR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('434','Libya','LBY');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('438','Liechtenstein','LIE');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('440','Lithuania','LTU');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('442','Luxembourg','LUX');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('450','Madagascar','MDG');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('454','Malawi','MWI');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('458','Malaysia','MYS');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('462','Maldives','MDV');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('466','Mali','MLI');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('470','Malta','MLT');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('584','Marshall Islands','MHL');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('474','Martinique','MTQ');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('478','Mauritania','MRT');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('480','Mauritius','MUS');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('175','Mayotte','MYT');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('484','Mexico','MEX');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('583','Micronesia (Federated States of)','FSM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('492','Monaco','MCO');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('496','Mongolia','MNG');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('499','Montenegro','MNE');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('500','Montserrat','MSR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('504','Morocco','MAR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('508','Mozambique','MOZ');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('104','Myanmar','MMR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('516','Namibia','NAM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('520','Nauru','NRU');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('524','Nepal','NPL');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('528','Netherlands','NLD');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('540','New Caledonia','NCL');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('554','New Zealand','NZL');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('558','Nicaragua','NIC');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('562','Niger','NER');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('566','Nigeria','NGA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('570','Niue','NIU');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('574','Norfolk Island','NFK');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('580','Northern Mariana Islands','MNP');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('578','Norway','NOR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('275','Occupied Palestinian Territory','PSE');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('512','Oman','OMN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('586','Pakistan','PAK');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('585','Palau','PLW');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('591','Panama','PAN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('598','Papua New Guinea','PNG');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('600','Paraguay','PRY');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('604','Peru','PER');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('608','Philippines','PHL');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('612','Pitcairn','PCN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('616','Poland','POL');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('620','Portugal','PRT');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('630','Puerto Rico','PRI');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('634','Qatar','QAT');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('410','Republic of Korea','KOR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('498','Republic of Moldova','MDA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('638','Réunion','REU');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('642','Romania','ROU');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('643','Russian Federation','RUS');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('646','Rwanda','RWA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('652','Saint-Barthélemy','BLM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('654','Saint Helena','SHN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('659','Saint Kitts and Nevis','KNA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('662','Saint Lucia','LCA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('663','Saint-Martin (French part)','MAF');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('666','Saint Pierre and Miquelon','SPM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('670','Saint Vincent and the Grenadines','VCT');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('882','Samoa','WSM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('674','San Marino','SMR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('678','Sao Tome and Principe','STP');

INSERT INTO countries (`country_numerical_code`,`country_name`) VALUES ('680','Sark');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('682','Saudi Arabia','SAU');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('686','Senegal','SEN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('688','Serbia','SRB');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('690','Seychelles','SYC');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('694','Sierra Leone','SLE');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('702','Singapore','SGP');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('534','Sint Maarten (Dutch part)','SXM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('703','Slovakia','SVK');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('705','Slovenia','SVN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('90','Solomon Islands','SLB');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('706','Somalia','SOM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('710','South Africa','ZAF');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('728','South Sudan','SSD');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('724','Spain','ESP');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('144','Sri Lanka','LKA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('729','Sudan','SDN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('740','Suriname','SUR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('744','Svalbard and Jan Mayen Islands','SJM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('748','Swaziland','SWZ');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('752','Sweden','SWE');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('756','Switzerland','CHE');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('760','Syrian Arab Republic','SYR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('762','Tajikistan','TJK');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('764','Thailand','THA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('807','The former Yugoslav Republic of Macedonia','MKD');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('626','Timor-Leste','TLS');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('768','Togo','TGO');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('772','Tokelau','TKL');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('776','Tonga','TON');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('780','Trinidad and Tobago','TTO');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('788','Tunisia','TUN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('792','Turkey','TUR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('795','Turkmenistan','TKM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('796','Turks and Caicos Islands','TCA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('798','Tuvalu','TUV');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('800','Uganda','UGA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('804','Ukraine','UKR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('784','United Arab Emirates','ARE');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('826','United Kingdom of Great Britain and Northern Ireland','GBR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('834','United Republic of Tanzania','TZA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('840','United States of America','USA');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('850','United States Virgin Islands','VIR');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('858','Uruguay','URY');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('860','Uzbekistan','UZB');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('548','Vanuatu','VUT');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('862','Venezuela (Bolivarian Republic of)','VEN');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('704','Viet Nam','VNM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('876','Wallis and Futuna Islands','WLF');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('732','Western Sahara','ESH');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('887','Yemen','YEM');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('894','Zambia','ZMB');

INSERT INTO countries (`country_numerical_code`,`country_name`,`country_ISO3`) VALUES ('716','Zimbabwe','ZWE');

